### ISSUE TITLE
gcc 8.3 ?

### ISSUE THREAD

**Issue by nicolai86** [ARMmbed/homebrew-formulae#23]
Hey,

first of, thanks so much for this tap!

I'm wondering if it needs to be upgrade for the [gcc 8.3](https://gcc.gnu.org/) which was releases on 2019-02-22?

```
$ arm-none-eabi-gcc -v
Using built-in specs.
...
gcc version 8.2.1 20181213 (release) [gcc-8-branch revision 267074] (GNU Tools for Arm Embedded Processors 8-2018-q4-major)
```

I'm on the latest version of the formula:

```
# brew info arm-none-eabi-gcc
armmbed/formulae/arm-none-eabi-gcc: stable 8-2018-q4-major
https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
/Users/nicolai86/homebrew/Cellar/arm-none-eabi-gcc/8-2018-q4-major (5,803 files, 511.4MB)
  Built from source on 2019-02-23 at 21:42:42
From: https://github.com/armmbed/homebrew-formulae/blob/master/arm-none-eabi-gcc.rb
```

**Comment by justacec** [comment]
I just created a pull request (#25) to update the package to the most recent release by ARM.  (View at [https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm))  This package, based on the release notes, has gcc-8-branch revision 273027.  GCC version 8.3 was tagged as 269117.  As long as the Revs are incremental, it seems as though ARM's latest release includes gcc 8.3. (View at [https://gcc.gnu.org/viewcvs/gcc/tags/gcc_8_3_0_release/?sortby=file&pathrev=273027](https://gcc.gnu.org/viewcvs/gcc/tags/gcc_8_3_0_release/?sortby=file&pathrev=273027))

**Comment by Patater** [comment]
We've merged https://github.com/ARMmbed/homebrew-formulae/pull/27 to get today's latest GNU Arm Embedded Toolchain version.

**Comment by nicolai86** [comment]
Thank you!
